version: "3"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: k2j3k4l5m
      MYSQL_DATABASE: reactive-erp
      MYSQL_USER: reactive_erp_user
      MYSQL_PASSWORD: 1k2j3k4l5m
    ports:
      - "3307:3306"
