import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "../utils/api";
import { useRouter } from "next/router";

const UserComponent: React.FC<{ emailAddress: string | undefined }> = ({
  emailAddress = "",
}) => {
  const { useQuery } = api.users.getUser;
  const { data, error, isLoading } = useQuery(
    { email: emailAddress },
    {
      enabled: !!emailAddress,
    }
  );

  return <></>;
};

const Home: NextPage = () => {
  const { user, isLoaded } = useUser();
  const router = useRouter();

  React.useEffect(() => {
    if (isLoaded && !user) {
      router.push("/sign-in").catch((err) => {
        console.error(err);
      });
    }
  }, [isLoaded, router, user]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {user ? (
          <div className="text-white">
            <h1 className="text-4xl font-bold">Welcome {user.fullName}!</h1>
            <p className="text-xl">You are signed in.</p>
            <UserComponent
              emailAddress={user.primaryEmailAddress?.emailAddress}
            />
            <SignOutButton>
              <button className="btn">Sign out</button>
            </SignOutButton>
          </div>
        ) : (
          <></>
        )}
      </main>
    </>
  );
};

export default Home;
