import { type NextPage } from "next";
import Head from "next/head";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const { user } = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {user ? (
          <div className="text-white">
            <h1 className="text-4xl font-bold">Welcome {user.fullName}!</h1>
            <p className="text-xl">You are signed in.</p>
            <SignOutButton>
              <button className="btn">Sign out</button>
            </SignOutButton>
          </div>
        ) : (
          <div className="text-white">
            <h1 className="text-4xl font-bold">Welcome!</h1>
            <p className="text-xl">You are not signed in.</p>
            <SignInButton mode="modal">
              <button className="btn">Sign in</button>
            </SignInButton>
            <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
